export const CATEGORIES_ACTION_TYPE = {
    FETCH_CATEGORIES_START: "category/FETCH_CATEGORIES_START",
    FETCH_CATEGORIES_SUCCES: "category/FETCH_CATEGORIES_SUCCES",
    FETCH_CATEGORIES_FAIL: "category/FETCH_CATEGORIES_FAIL"
}